# azure-pipelines.yml

trigger:
  branches:
    include:
      - main
      - master

pool:
  name: 'Self-Hosted'

steps:
# Step 1: Restore dependencies
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0'
  displayName: 'Install .NET SDK'

- script: |
    dotnet restore
  displayName: 'Restore dependencies'

# Step 2: Build the solution
- script: |
    dotnet build --configuration Release
  displayName: 'Build the project'

# Step 4: Publish build output
- script: |
    dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish build output'

# Step 5: Publish artifacts
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
  displayName: 'Publish Artifact'
