# azure-pipelines.yml

trigger:
  branches:
    include:
      - main
      - master

pool:
  name: 'Self-Hosted-Agent-Pool' # Replace with your agent pool name

steps:
# Step 1: Install dependencies
- task: UseNode@2
  inputs:
    versionSpec: '16.x'
  displayName: 'Set up Node.js'

# Step 2: Install project dependencies
- script: |
    npm install
  displayName: 'Install dependencies'

# Step 3: Run build command
- script: |
    npm run build
  displayName: 'Run build'

# Step 4: Publish artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/dist'
    artifact: 'drop'
  displayName: 'Publish Artifact'
